name: Frontend CI Workflow

on: 
  workflow_call: 
    # secrets:
    #   AWS_ACCESS_KEY_ID:
    #     required: true
    #   AWS_SECRET_ACCESS_KEY:
    #     required: true
jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # Não entendi pq não é bom usar esse v4, estudar depois
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci # Melhor do que install, pq usa o package-lock, não corre risco de usar outras versões

      - name: Validate frontend
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: integration
    permissions:
      # contents: read # Permite que o checkout leia o repo
      id-token: write # Permite que o workflow solicite o OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::808826729764:role/GitHubActions-FrontendDeploy
          aws-region: us-east-1

      - name: Upload files to S3
        run: |
          aws s3 sync ./src s3://aws-full-project-frontend

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3E75WBZWAJEIM \
            --paths "/*"