name: Security Gate

on:
  workflow_call: 

jobs:
  sast_analysis:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript

      - name: Analyze
        uses: github/codeql-action/analyze@v4
        with:
          category: "/security:javascript-typescript"

  security_gate:
    needs: sast_analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: read
      actions: read
      contents: read
    steps:
      - name: Fail PR if critical/high alerts found
        uses: tspascoal/fail-workflow-on-alerts-action@v0
        with:
          max_errors: 0     # qualquer alerta "error"/critical-high falha o gate
          max_warnings: -1  # -1 = não considera esse nível
          max_notes: -1
          max_unknowns: -1
          max_none: -1